# Generated by Django 5.1.3 on 2025-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_order_purchased_items_purchaseditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
