# Generated by Django 5.1.3 on 2025-06-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_purchaseditem_quantity"),
        ("products", "0008_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingdetails",
            name="status",
            field=models.CharField(
                choices=[("ARCHIVED", "Archived"), ("ACTIVE", "Active")],
                default="ACTIVE",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchaseditem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.product"
            ),
        ),
    ]
