# Generated by Django 5.1.3 on 2025-06-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_shippingdetails_status_alter_purchaseditem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingdetails",
            name="status",
            field=models.CharField(
                choices=[("archived", "Archived"), ("active", "Active")],
                default="active",
                max_length=20,
            ),
        ),
    ]
