# Generated by Django 5.1.3 on 2025-06-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_shippingdetails_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingdetails',
            options={'verbose_name_plural': 'Shipping Details'},
        ),
    ]
