# Generated by Django 5.1.3 on 2025-07-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_shippingdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='save_details',
            field=models.BooleanField(default=False, help_text='Save shipping details for future orders'),
        ),
    ]
