# Generated by Django 5.1.3 on 2025-10-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_paymentdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name_plural': 'Payment Details'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.paymentdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_security_code',
            field=models.CharField(max_length=3),
        ),
    ]
