# Generated by Django 5.0.7 on 2024-08-28 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_published',
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
