# Generated by Django 5.1.3 on 2024-12-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO products_productimage (product_id, image)
            SELECT
                id as product_id,
                image
            FROM products_product
            WHERE image IS NOT NULL AND image != '';
            """,
            reverse_sql="""
            DELETE FROM products_productImage;
            """
        )
    ]
