# Generated by Django 5.1.3 on 2025-01-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
    ]
