# Generated by Django 5.1.3 on 2025-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("ARCHIVED", "Archived"), ("ACTIVE", "Active")],
                default="ACTIVE",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
